"""Narrow durable workflow repository contract."""
from __future__ import annotations
from typing import Protocol
from uuid import UUID

from models.workflow import MigrationAuditEvent,MigrationWorkflow,MigrationWorkflowStatus,WorkflowArtifact

class WorkflowRepository(Protocol):
 def create_workflow(self,workflow:MigrationWorkflow,event:MigrationAuditEvent,*,idempotency_key:str,request_hash:str)->MigrationWorkflow:...
 def get_workflow(self,workflow_id:UUID)->MigrationWorkflow:...
 def transition_status(self,workflow_id:UUID,expected_version:int,new_status:MigrationWorkflowStatus,event:MigrationAuditEvent,*,last_error_code:str|None,idempotency_key:str,request_hash:str)->MigrationWorkflow:...
 def append_artifact(self,workflow_id:UUID,expected_version:int,artifact:WorkflowArtifact,event:MigrationAuditEvent,*,idempotency_key:str,request_hash:str)->tuple[MigrationWorkflow,WorkflowArtifact]:...
 def mark_failed(self,*args,**kwargs)->MigrationWorkflow:...
 def cancel_workflow(self,*args,**kwargs)->MigrationWorkflow:...
 def list_artifacts(self,workflow_id:UUID,*,offset:int=0,limit:int=100)->tuple[WorkflowArtifact,...]:...
 def list_audit_events(self,workflow_id:UUID,*,offset:int=0,limit:int=100)->tuple[MigrationAuditEvent,...]:...
 def close(self)->None:...
