"""Narrow durable workflow repository contract."""
from __future__ import annotations
from typing import Protocol
from uuid import UUID

from schemabridge.models.execution import MigrationExecutionAttempt, MigrationExecutionEvidence
from schemabridge.models.validation import MigrationValidationExecutionReport
from schemabridge.models.workflow_validation import WorkflowValidationRun
from schemabridge.models.workflow import MigrationAuditEvent,MigrationWorkflow,MigrationWorkflowStatus,WorkflowArtifact

class WorkflowRepository(Protocol):
 def create_workflow(self,workflow:MigrationWorkflow,event:MigrationAuditEvent,*,idempotency_key:str,request_hash:str)->MigrationWorkflow:...
 def get_workflow(self,workflow_id:UUID)->MigrationWorkflow:...
 def transition_status(self,workflow_id:UUID,expected_version:int,new_status:MigrationWorkflowStatus,event:MigrationAuditEvent,*,last_error_code:str|None,idempotency_key:str,request_hash:str)->MigrationWorkflow:...
 def append_artifact(self,workflow_id:UUID,expected_version:int,artifact:WorkflowArtifact,event:MigrationAuditEvent,*,idempotency_key:str,request_hash:str)->tuple[MigrationWorkflow,WorkflowArtifact]:...
 def append_artifact_operation(self,workflow_id:UUID,expected_version:int,artifact:WorkflowArtifact,artifact_event:MigrationAuditEvent,*,new_status:MigrationWorkflowStatus|None,transition_event:MigrationAuditEvent|None,idempotency_key:str,request_hash:str)->tuple[MigrationWorkflow,WorkflowArtifact]:...
 def mark_failed(self,*args,**kwargs)->MigrationWorkflow:...
 def cancel_workflow(self,*args,**kwargs)->MigrationWorkflow:...
 def list_artifacts(self,workflow_id:UUID,*,offset:int=0,limit:int=100)->tuple[WorkflowArtifact,...]:...
 def get_artifact(self,workflow_id:UUID,artifact_version:int)->WorkflowArtifact|None:...
 def get_artifact_by_id(self,workflow_id:UUID,artifact_id:UUID)->WorkflowArtifact|None:...
 def get_latest_artifact(self,workflow_id:UUID,artifact_type)->WorkflowArtifact|None:...
 def get_execution_attempt_by_command(self,workflow_id:UUID,idempotency_key:str,request_hash:str)->MigrationExecutionAttempt|None:...
 def claim_execution_attempt(self,workflow_id:UUID,expected_version:int,attempt:MigrationExecutionAttempt,event:MigrationAuditEvent,*,idempotency_key:str,request_hash:str)->tuple[MigrationWorkflow,MigrationExecutionAttempt,bool]:...
 def mark_execution_running(self,attempt_id:UUID,running_at)->tuple[MigrationExecutionAttempt,bool]:...
 def complete_execution_attempt(self,workflow_id:UUID,expected_version:int,attempt_id:UUID,evidence:MigrationExecutionEvidence,artifact:WorkflowArtifact,artifact_event:MigrationAuditEvent,new_status:MigrationWorkflowStatus,transition_event:MigrationAuditEvent)->tuple[MigrationWorkflow,MigrationExecutionAttempt,WorkflowArtifact]:...
 def get_execution_attempt(self,attempt_id:UUID)->MigrationExecutionAttempt:...
 def get_validation_run_by_command(self,workflow_id:UUID,idempotency_key:str,request_hash:str)->WorkflowValidationRun|None:...
 def claim_validation_run(self,workflow_id:UUID,expected_version:int,run:WorkflowValidationRun,artifact:WorkflowArtifact,artifact_event:MigrationAuditEvent,transition_event:MigrationAuditEvent,*,idempotency_key:str,request_hash:str)->tuple[MigrationWorkflow,WorkflowValidationRun,WorkflowArtifact,bool]:...
 def mark_validation_running(self,run_id:UUID,running_at)->tuple[WorkflowValidationRun,bool]:...
 def complete_validation_run(self,workflow_id:UUID,expected_version:int,run_id:UUID,report:MigrationValidationExecutionReport|None,artifact:WorkflowArtifact|None,artifact_event:MigrationAuditEvent|None,new_status:MigrationWorkflowStatus,transition_event:MigrationAuditEvent,*,completed_at,failure_category:str|None)->tuple[MigrationWorkflow,WorkflowValidationRun,WorkflowArtifact|None]:...
 def get_validation_run(self,run_id:UUID)->WorkflowValidationRun:...
 def list_audit_events(self,workflow_id:UUID,*,offset:int=0,limit:int=100)->tuple[MigrationAuditEvent,...]:...
 def close(self)->None:...
