"""Read and reconcile exact primary keys in bounded, read-only batches."""

from __future__ import annotations

from collections import Counter
from collections.abc import Callable, Iterator
from dataclasses import dataclass
from typing import Hashable

from schemabridge.models.mapping import SqlDialect
from schemabridge.models.validation import PrimaryKeyReconciliation
from schemabridge.validation.sql import _quote


@dataclass(frozen=True, slots=True)
class GeneratedPrimaryKeyBatchSql:
    """One bounded primary-key read generated by SchemaBridge."""

    dialect: SqlDialect
    sql: str
    relation: tuple[str, ...]
    key_columns: tuple[str, ...]
    metric_aliases: tuple[str, ...]
    offset: int
    limit: int


def compile_primary_key_batch_sql(
    *,
    dialect: SqlDialect,
    relation: tuple[str, ...],
    key_columns: tuple[str, ...],
    offset: int,
    limit: int,
) -> GeneratedPrimaryKeyBatchSql:
    """Compile an ordered, bounded key query with only validated identifiers.

    ``LIMIT`` and ``OFFSET`` are validated integers rendered by the compiler,
    rather than request-controlled SQL fragments.  Connector row caps can still
    lower the limit before execution.
    """

    if (
        not isinstance(dialect, SqlDialect)
        or not isinstance(relation, tuple)
        or not relation
        or not isinstance(key_columns, tuple)
        or not key_columns
        or isinstance(offset, bool)
        or not isinstance(offset, int)
        or offset < 0
        or isinstance(limit, bool)
        or not isinstance(limit, int)
        or limit <= 0
    ):
        raise ValueError("Invalid primary-key batch request.")
    expected_relation_parts = 3 if dialect is SqlDialect.SNOWFLAKE else 2
    if len(relation) != expected_relation_parts:
        raise ValueError("Invalid primary-key batch relation.")
    aliases = tuple(f"key_{index:03d}" for index in range(len(key_columns)))
    quoted_relation = ".".join(_quote(dialect, value) for value in relation)
    projections = ", ".join(
        f"{_quote(dialect, column)} AS {_quote(dialect, alias)}"
        for column, alias in zip(key_columns, aliases, strict=True)
    )
    order_by = ", ".join(f"{_quote(dialect, column)} ASC" for column in key_columns)
    return GeneratedPrimaryKeyBatchSql(
        dialect=dialect,
        sql=(
            f"SELECT {projections} FROM {quoted_relation} "
            f"ORDER BY {order_by} LIMIT {limit} OFFSET {offset}"
        ),
        relation=relation,
        key_columns=key_columns,
        metric_aliases=aliases,
        offset=offset,
        limit=limit,
    )


def _rows(result: object, expected_aliases: tuple[str, ...]) -> tuple[tuple[Hashable, ...], ...]:
    """Normalize a generated key-query result without accepting ambiguous data."""

    columns = getattr(result, "columns", None)
    values = getattr(result, "rows", None)
    if not isinstance(columns, (tuple, list)) or not isinstance(values, (tuple, list)):
        raise ValueError("Malformed primary-key batch result.")
    names = tuple(str(value).casefold() for value in columns)
    expected = tuple(value.casefold() for value in expected_aliases)
    if names != expected:
        raise ValueError("Malformed primary-key batch result.")
    normalized = []
    for row in values:
        if isinstance(row, dict):
            by_name = {str(name).casefold(): value for name, value in row.items()}
            if tuple(by_name) != names:
                raise ValueError("Malformed primary-key batch result.")
            key = tuple(by_name[name] for name in names)
        elif isinstance(row, (tuple, list)) and len(row) == len(names):
            key = tuple(row)
        else:
            raise ValueError("Malformed primary-key batch result.")
        if not all(isinstance(value, Hashable) for value in key):
            raise ValueError("Malformed primary-key batch result.")
        normalized.append(key)
    return tuple(normalized)


def read_primary_key_batches(
    execute: Callable[..., object],
    *,
    dialect: SqlDialect,
    relation: tuple[str, ...],
    key_columns: tuple[str, ...],
    batch_size: int,
    timeout_seconds: int | None,
) -> Iterator[tuple[tuple[Hashable, ...], ...]]:
    """Yield every key batch, advancing by returned rows until an empty batch."""

    if not callable(execute):
        raise TypeError("Primary-key batch executor must be callable.")
    offset = 0
    while True:
        generated = compile_primary_key_batch_sql(
            dialect=dialect,
            relation=relation,
            key_columns=key_columns,
            offset=offset,
            limit=batch_size,
        )
        result = execute(
            sql=generated.sql,
            parameters=(),
            timeout_seconds=timeout_seconds,
            max_rows=batch_size,
        )
        batch = _rows(result, generated.metric_aliases)
        if len(batch) > batch_size:
            raise ValueError("Malformed primary-key batch result.")
        if not batch:
            return
        yield batch
        offset += len(batch)


def reconcile_primary_key_batches(
    source_batches: Iterator[tuple[tuple[Hashable, ...], ...]],
    target_batches: Iterator[tuple[tuple[Hashable, ...], ...]],
) -> PrimaryKeyReconciliation:
    """Compare exact key multisets while retaining only aggregate evidence."""

    source = Counter(key for batch in source_batches for key in batch)
    target = Counter(key for batch in target_batches for key in batch)
    return PrimaryKeyReconciliation(
        source_key_count=sum(source.values()),
        target_key_count=sum(target.values()),
        missing_key_count=sum((source - target).values()),
        extra_key_count=sum((target - source).values()),
        source_duplicate_key_count=sum(count - 1 for count in source.values() if count > 1),
        target_duplicate_key_count=sum(count - 1 for count in target.values() if count > 1),
    )


__all__ = [
    "GeneratedPrimaryKeyBatchSql",
    "PrimaryKeyReconciliation",
    "compile_primary_key_batch_sql",
    "read_primary_key_batches",
    "reconcile_primary_key_batches",
]
